version: '3'

services:
  mysql-db:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'app'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "54321:3306"